### ISSUE TITLE
some codes are missing

### ISSUE THREAD

**Issue by luolanfeixue** [facebookresearch/SentAugment#1]
sase.py  line 19-21

from src.utils import AttrDict
from src.data.dictionary import Dictionary, BOS_WORD, EOS_WORD, PAD_WORD, UNK_WORD, MASK_WORD
from src.model.transformer import TransformerModel

the github don't have src.utils src.data and src.model. could you push the code?

**Comment by jingfeidu** [comment]
Hi this should come from XLM(https://github.com/facebookresearch/XLM) code base which is the dependent repo for this project. We will add code for managing the dependencies soon.
